web:
  build: .
  container_name: consumer
  command: thin start
  command: rake sneakers:run
  volumes:
    - .:/consumer
  ports:
    - "9000:3000"
  links:
    - redis
  external_links:
    - message

redis:
  image: redis
  container_name: consumer_redis