web:
  build: .
  command: thin start
  command: rake sneakers:run
  volumes:
    - .:/consumer
  ports:
    - "9000:3000"
  links:
    - redis
  external_links:
    - rails_message_1

redis:
  image: redis