source 'https://ruby.taobao.org'

gem 'rails'
gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'

gem 'mysql2', '~> 0.3.0'
gem 'bunny'

group :development do
  gem 'spring'
end